"""
Flask YOLO 微服务配置
"""
import os

# 服务端口
PORT = int(os.environ.get("YOLO_SERVICE_PORT", 5000))

# 模型路径（自动从ultralytics下载yolov8n.pt）
MODEL_NAME = os.environ.get("YOLO_MODEL_NAME", "yolov8n.pt")

# 失物场景中应忽略的类别（人物、动物、交通工具等不会被误认为失物）
IGNORE_CATEGORIES = {
    "person", "bicycle", "car", "motorcycle", "airplane", "bus", "train",
    "truck", "boat", "traffic light", "fire hydrant", "stop sign",
    "parking meter", "bench", "bird", "cat", "dog", "horse", "sheep",
    "cow", "elephant", "bear", "zebra", "giraffe", "potted plant", "sink",
}

# COCO数据集80类 → 中文映射（完整版）
COCO_CATEGORIES_CN = {
    # --- 人物/动物/交通工具（通常忽略） ---
    "person": "人物",
    "bicycle": "自行车",
    "car": "汽车",
    "motorcycle": "摩托车",
    "airplane": "飞机",
    "bus": "公交车",
    "train": "火车",
    "truck": "卡车",
    "boat": "船",
    "traffic light": "交通灯",
    "fire hydrant": "消防栓",
    "stop sign": "停止标志",
    "parking meter": "停车计时器",
    "bench": "长椅",
    "bird": "鸟",
    "cat": "猫",
    "dog": "狗",
    "horse": "马",
    "sheep": "羊",
    "cow": "牛",
    "elephant": "大象",
    "bear": "熊",
    "zebra": "斑马",
    "giraffe": "长颈鹿",
    "frisbee": "飞盘",
    "skis": "滑雪板",
    "kite": "风筝",
    "potted plant": "盆栽",
    "sink": "水槽",
    # --- 常见失物 ---
    "backpack": "书包",
    "handbag": "手提包",
    "suitcase": "行李箱",
    "bottle": "水杯",
    "wine glass": "玻璃杯",
    "cup": "杯子",
    "fork": "叉子",
    "knife": "刀",
    "spoon": "勺子",
    "bowl": "碗",
    "banana": "香蕉",
    "apple": "苹果",
    "orange": "橙子",
    "sandwich": "三明治",
    "broccoli": "西兰花",
    "carrot": "胡萝卜",
    "hot dog": "热狗",
    "pizza": "披萨",
    "donut": "甜甜圈",
    "cake": "蛋糕",
    "chair": "椅子",
    "couch": "沙发",
    "bed": "床",
    "dining table": "餐桌",
    "toilet": "马桶",
    "tv": "电视",
    "laptop": "笔记本电脑",
    "mouse": "鼠标",
    "remote": "遥控器",
    "keyboard": "键盘",
    "cell phone": "手机",
    "microwave": "微波炉",
    "oven": "烤箱",
    "toaster": "烤面包机",
    "refrigerator": "冰箱",
    "book": "书",
    "clock": "时钟",
    "vase": "花瓶",
    "scissors": "剪刀",
    "teddy bear": "泰迪熊",
    "hair drier": "吹风机",
    "toothbrush": "牙刷",
    "umbrella": "雨伞",
    "sports ball": "运动球",
    "tennis racket": "网球拍",
    "baseball bat": "棒球棒",
    "baseball glove": "棒球手套",
    "skateboard": "滑板",
    "surfboard": "冲浪板",
    "snowboard": "滑雪板",
    "sunglasses": "太阳镜",
    "tie": "领带",
    "wallet": "钱包",
    "watch": "手表",
    "glasses": "眼镜",
    "hat": "帽子",
    "scarf": "围巾",
    "jacket": "外套",
    "coat": "大衣",
    "shirt": "衬衫",
    "pants": "裤子",
    "shoes": "鞋子",
    "socks": "袜子",
    "glove": "手套",
}
